### **2.  Operazioni su array**
Crea un array **a**, 2D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente la sua 2ª e 4ª riga, e **c** contenente solo la 3ª.  Dividi ogni colonna dell'array a, elemento per elemento, con l'array c.

In [1]:
import numpy as np

# 1. Crea un array a
a = np.arange(15).reshape(5, 3)
print("Array a:\n", a)

# 2. Array b con la seconda e la quarta riga di a
b = a[1:4:2,]
print("Array b (2ª e 4ª riga):\n", b)

# 3. Array c con la terza riga di a
c = a[2,]
print("Array c (3ª riga):\n", c)

# 4. Divisione
print("Divisione a / c:\n", a/c)

Array a:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Array b (2ª e 4ª riga):
 [[ 3  4  5]
 [ 9 10 11]]
Array c (3ª riga):
 [6 7 8]
Divisione a / c:
 [[0.         0.14285714 0.25      ]
 [0.5        0.57142857 0.625     ]
 [1.         1.         1.        ]
 [1.5        1.42857143 1.375     ]
 [2.         1.85714286 1.75      ]]
